version: '3.9'

services:
  # ----------------------
  # Zookeeper
  # ----------------------
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "2181"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ----------------------
  # Kafka Broker
  # ----------------------
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      zookeeper:
          condition: service_healthy
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    healthcheck:
      test:
        [
          'CMD',
          'kafka-topics',
          '--bootstrap-server',
          'localhost:9092',
          '--list'
        ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  # ----------------------
  # Kafka Connect
  # ----------------------
  kafka-connect:
    image: debezium/connect:2.2
    platform: linux/amd64
    container_name: kafka-connect
    depends_on:
      - kafka
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: "connect-cluster"
      CONFIG_STORAGE_TOPIC: 'connect-configs'
      OFFSET_STORAGE_TOPIC: 'connect-offsets'
      STATUS_STORAGE_TOPIC: 'connect-status'
      CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE: 'false'
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: 'false'
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_REST_ADVERTISED_HOST_NAME: kafka-connect
      CONNECT_PLUGIN_PATH: /kafka/connect
    ports:
      - "8083:8083"

  # ----------------------
  # PostgreSQL API Gateway
  # ----------------------
  postgres-auth:
    image: postgres:16-alpine
    container_name: postgres-auth
    environment:
      POSTGRES_USER: maxramirez
      POSTGRES_PASSWORD: 22leorexx100
      POSTGRES_DB: auth_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U maxramirez"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: >
      postgres -c wal_level=logical
               -c max_replication_slots=5
               -c max_wal_senders=5
               -c listen_addresses='*'
    ports:
      - "5433:5432"
    volumes:
      - pgdata_auth:/var/lib/postgresql/data

  # ----------------------
  # PostgreSQL Nutritional Advice
  # ----------------------
  postgres-nutritional:
    image: postgres:16-alpine
    container_name: postgres-nutritional
    environment:
      POSTGRES_USER: maxramirez
      POSTGRES_PASSWORD: 22leorexx100
      POSTGRES_DB: nutritional_advice
    command: >
      postgres -c wal_level=logical
               -c max_replication_slots=5
               -c max_wal_senders=5
               -c listen_addresses='*'
    ports:
      - "5432:5432"
    volumes:
      - pgdata_nutritional:/var/lib/postgresql/data

  # ----------------------
  # PostgreSQL Delivery
  # ----------------------
  postgres-delivery:
    image: postgres:16-alpine
    container_name: postgres-delivery
    environment:
      POSTGRES_USER: maxramirez
      POSTGRES_PASSWORD: 22leorexx100
      POSTGRES_DB: delivery_db
    command: >
      postgres -c wal_level=logical
               -c max_replication_slots=5
               -c max_wal_senders=5
               -c listen_addresses='*'
    ports:
      - "5435:5432"
    volumes:
      - pgdata_delivery:/var/lib/postgresql/data

  # ----------------------
  # API Gateway
  # ----------------------
  api-gateway:
    build:
      context: ./api-gateway-nur-grupo1
      cache_from:
        - api-gateway:latest
    container_name: api-gateway
    env_file:
      - ./api-gateway-nur-grupo1/.env
    ports:
      - "4000:4000"
    depends_on:
      kafka:
          condition: service_healthy
      postgres-auth:
          condition: service_healthy
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:4000/health"
        ]
      interval: 10s
      timeout: 5s
      start_period: 20s

  # ----------------------
  # Auth Service
  # ----------------------
  auth-service:
    build:
      context: ./ms-auth-service
    container_name: ms-auth-service
    env_file:
      - ./ms-auth-service/.env
    ports:
      - "3500:3000"
    depends_on:
      postgres-auth:
        condition: service_healthy
    restart: unless-stopped

  # ----------------------
  # Nutritional Advice Microservice
  # ----------------------
  nutritional-advice:
    build:
      context: ./nutritional-advice-microservice
    container_name: nutritional-advice
    env_file:
      - ./nutritional-advice-microservice/.env
    ports:
      - "3001:3000"
    depends_on:
      - kafka
      - postgres-nutritional
    restart: unless-stopped

  # ----------------------
  # Delivery Microservice
  # ----------------------
  delivery:
    build:
      context: ./delivery-microservice_nur
    container_name: delivery
    env_file:
      - ./delivery-microservice_nur/.env
    ports:
      - "3100:3000"
    depends_on:
      - kafka
      - postgres-delivery


volumes:
  pgdata_auth:
  pgdata_nutritional:
  pgdata_delivery: