services:

  # ----------------------
  # ZOOKEEPER
  # ----------------------
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  # ----------------------
  # KAFKA
  # ----------------------
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      # 🔥 CLAVE: doble listener (interno + externo)
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
      - "29092:29092"

  # ----------------------
  # KAFKA CONNECT (DEBEZIUM)
  # ----------------------
  kafka-connect:
    image: debezium/connect:2.2
    container_name: kafka-connect
    depends_on:
      - kafka
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: connect-cluster
      CONFIG_STORAGE_TOPIC: connect-configs
      OFFSET_STORAGE_TOPIC: connect-offsets
      STATUS_STORAGE_TOPIC: connect-status
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_REST_ADVERTISED_HOST_NAME: kafka-connect
    ports:
      - "8083:8083"

  # ----------------------
  # POSTGRES AUTH
  # ----------------------
  postgres-auth:
    image: postgres:16-alpine
    container_name: postgres-auth
    environment:
      POSTGRES_USER: maxramirez
      POSTGRES_PASSWORD: 22leorexx100
      POSTGRES_DB: auth_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata_auth:/var/lib/postgresql/data

    # 🔥 FIX DEL ERROR
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U maxramirez -d auth_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ----------------------
  # POSTGRES NUTRITIONAL
  # ----------------------
  postgres-nutritional:
    image: postgres:16-alpine
    container_name: postgres-nutritional
    environment:
      POSTGRES_USER: maxramirez
      POSTGRES_PASSWORD: 22leorexx100
      POSTGRES_DB: nutritional_advice
    ports:
      - "5434:5432"
    volumes:
      - pgdata_nutritional:/var/lib/postgresql/data

  # ----------------------
  # POSTGRES DELIVERY
  # ----------------------
  postgres-delivery:
    image: postgres:16-alpine
    container_name: postgres-delivery
    environment:
      POSTGRES_USER: maxramirez
      POSTGRES_PASSWORD: 22leorexx100
      POSTGRES_DB: delivery_db
    ports:
      - "5435:5432"
    volumes:
      - pgdata_delivery:/var/lib/postgresql/data
  
  # ----------------------
  # PostgreSQL Production
  # ----------------------
  postgres-production:
    image: postgres:16-alpine
    container_name: postgres-production
    environment:
      POSTGRES_USER: maxramirez
      POSTGRES_PASSWORD: 22leorexx100
      POSTGRES_DB: production_db
    command: >
      postgres -c wal_level=logical
               -c max_replication_slots=5
               -c max_wal_senders=5
               -c listen_addresses='*'
    ports:
      - "5436:5432"
    volumes:
      - pgdata_production:/var/lib/postgresql/data

  # ----------------------
  # AUTH SERVICE
  # ----------------------
  auth-service:
    build: ./ms-auth-service
    container_name: ms-auth-service
    #env_file:
    #  - ./ms-auth-service/.env
    ports:
      - "3500:3000"
    depends_on:
      postgres-auth:
        condition: service_healthy
    restart: unless-stopped

  # ----------------------
  # API GATEWAY
  # ----------------------
  api-gateway:
    build: ./api-gateway-nur-grupo1
    container_name: api-gateway
    #env_file:
    #  - ./api-gateway-nur-grupo1/.env
    ports:
      - "4000:4000"
    depends_on:
      postgres-auth:
        condition: service_healthy
      kafka:
        condition: service_started

  # ----------------------
  # MICROSERVICIOS
  # ----------------------
  nutritional-advice:
    build: ./nutritional-advice-microservice
    container_name: nutritional-advice
    #env_file:
    #  - ./nutritional-advice-microservice/.env
    ports:
      - "3001:3000"
    depends_on:
      - kafka
      - postgres-nutritional

  delivery:
    build: ./delivery-microservice_nur
    container_name: delivery
    env_file:
      - ./delivery-microservice_nur/.env
    ports:
      - "3100:3000"
    depends_on:
      - kafka
      - postgres-delivery

  # ----------------------
  # Production Microservice
  # ----------------------
  production:
    build:
      context: ./production-microservice-nur
    container_name: production
    #env_file:
    #  - ./production-microservice-nur/.env
    ports:
      - "3200:3000"
    depends_on:
      - kafka
      - postgres-production

  # -----------------------
  # Redis Service
  # -----------------------
  redis:
    image: redis:7.2-alpine
    container_name: redis-stack
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

  # ----------------------
  # Eureka Server
  # ----------------------
  eureka-server:
    build:
      context: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    restart: unless-stopped

  # ----------------------
  # API Gateway Spring
  # ----------------------
  api-gateway-spring:
    build:
      context: ./api-gateway-spring
    container_name: api-gateway-spring
    ports:
      - "9000:9000"
    depends_on:
      - eureka-server
    restart: unless-stopped

  # ----------------------
  # PostgreSQL for Contract Service
  # ----------------------
  postgres-contract-services:
    image: postgres:16
    container_name: postgres-contract-services
    environment:
      - POSTGRES_PASSWORD=Postgres2!
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pgdata_contract_services:/var/lib/postgresql/data
      - ./database-contract-services/src/main/resources/configuration/contract_services_init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./database-contract-services/src/main/resources/configuration/setup-debezium-postgres.sql:/docker-entrypoint-initdb.d/02-setup-debezium.sql
    ports:
      - "127.0.0.1:10001:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 30s
    command: |
      postgres 
      -c wal_level=logical 
      -c max_replication_slots=10 
      -c max_wal_senders=10
      -c max_connections=200
      -c shared_buffers=256MB
    restart: unless-stopped
    sysctls:
      - net.core.somaxconn=1024
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  # ----------------------
  # Database Migration Service
  # ----------------------
  database-contract-services:
    build:
      context: ./database-contract-services
    container_name: database-contract-services
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      postgres-contract-services:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-contract-services:5432/contract_services
      - SPRING_DATASOURCE_USERNAME=contract_services_user
      - SPRING_DATASOURCE_PASSWORD=KhQPnGzVYFs0BEyh8HwL
    restart: on-failure

  # ----------------------
  # Contract Services
  # ----------------------
  contract-services-microservice:
    build:
      context: ./contract-services-microservice
    container_name: contract-services-microservice
    ports:
      - "127.0.0.1:8440:8440"
    depends_on:
      database-contract-services:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-contract-services:5432/contract_services
      SPRING_DATASOURCE_USERNAME: contract_services_user
      SPRING_DATASOURCE_PASSWORD: KhQPnGzVYFs0BEyh8HwL
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_PROFILES_ACTIVE: docker
      SPRING_KAFKA_PRODUCER_KEY_SERIALIZER: org.apache.kafka.common.serialization.StringSerializer
      SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER: org.apache.kafka.common.serialization.StringSerializer
      SPRING_KAFKA_PROPERTIES_MAX_BLOCK_MS: 60000
    restart: on-failure

volumes:
  pgdata_auth:
  pgdata_nutritional:
  pgdata_delivery:
  pgdata_production:
  redis-data:
  pgdata_contract_services:
